### ISSUE TITLE
Struggling to run the lighting branch, Segfault

### ISSUE THREAD

**Issue by yourlocalcyborg** [solzilberman/3D_Cellular_Automata#1]
I'm on windows 11 running Debian on wsl2. I have an X server set up on VcXsrv for windows, and programs like xclock, xcalc, and glxgears run fine. It is very possible that I have something set wrong though, as I am unfamiliar with C++ development and especially this workflow for running X programs through wsl. The Issue is shown in the text below, and any help would be appreciated.

```
dirt@dirtwagon-pc:/mnt/e/OneDrive/Projects/clone/3D_Cellular_Automata$ make

g++ -g -std=c++11 main.cpp -lGL -lGLEW -lglut -o main

dirt@dirtwagon-pc:/mnt/e/OneDrive/Projects/clone/3D_Cellular_Automata$ ./main

Segmentation fault

**Comment by yourlocalcyborg** [comment]
This also happens on the "master" and "optimized" branches, so it's likely I have something configured wrong on my end.

**Comment by solzilberman** [comment]
I had to set these environment variables in wsl2 for it to compile properly:
```
export LIBGL_ALWAYS_INDIRECT=0
export LIBGL_ALWAYS_SOFTWARE=1
export MESA_GL_VERSION_OVERRIDE=3.3
```
I also launch VcXsrv via following command (note: native opengl option is disabled):
`/mnt/c/Program\ Files/VcXsrv/vcxsrv.exe :0 -multiwindow -clipboard -nowgl > /dev/null 2>&1 &`

I am running make from `~/...` rather than from `/mnt/c/...`.

Does setting `LIBGL_DEBUG=verbose` in wsl2 provide any more debug info? 

Please let me know if any of the above steps solve the issue or provides more debug info.

**Comment by yourlocalcyborg** [comment]
It seems that setting those environment variables and turning native opengl off has gotten it to work! Thanks for the help.
